model_name: a-06-24
mode: new
model_file: None

train:
  max_epoch: 40
  log_freq: 200
size:
  cropped_size: 64
  output_size: 128

dataloader:
  num_workers: 4
  batch_size: 16

optimizer:
  learning_rate: 3e-4
  adam_betas: 0.5, 0.999

loss:
  loss_weights:
    pixel: 1
    per: 0.4
    style: 2500
    adv: 0.0004


