model_name: 07-07
mode: new
model_file: new

train:
  max_epoch: 20
  log_freq: 400
size:
  cropped_size: 64
  output_size: 128

dataloader:
  num_workers: 4
  batch_size: 16

optimizer:
  learning_rate: 3e-4
  dis_learning_rate: 1e-4
  adam_betas: 0.9, 0.999

loss:
  loss_weights:
    pixel: 1
    ssim: 0.4
    per: 0.1
    style: 40000
    adv: 0.0004
